/*
CREATE TABLE USER_LOGIN IF NOT EXISTS (
  ID VARCHAR(20) NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  USER_PASSWORD VARCHAR(32) NOT NULL,
  CREATED_DATE DATE,
  PRIMARY KEY (ID)
);
INSERT INTO USER_LOGIN (ID, USER_NAME, USER_PASSWORD, CREATED_DATE) VALUES ('UX-L-000000000000000', 'demo', 'demo', CURRENT_DATE()); 
*/

